title: Lady Knight
description: Unicorns and talking cats and lots of magic sparkles.
permalink: none
paginate: 5
paginate_path: "page:num/"
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jekyll-paginate
  - jekyll-feed
gems:
  - jekyll-paginate
  - jekyll-feed
