title: Lady Knight  
logo: http://danaamundsen.site44.com/ladyknight/logo.png
description: Unicorns and talking cats and lots of magic sparkles.
paginate: 1
paginate_path: "/webcomic/page:num/"
permalink: none
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal
plugins: 
  - jekyll-paginate
  - jekyll-feed
gems:
  - jekyll-paginate
  - jekyll-feed
